# Generated by Django 5.1.4 on 2024-12-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, choices=[('DEVELOPPEMENT WEB', 'DEVELOPPEMENT WEB'), ('MARKETING DIGITAL', 'MARKETING DIGITAL'), ('DEVELOPPEMENT WEB', 'DEVELOPPEMENT WEB')], max_length=255, null=True),
        ),
    ]
