# Generated by Django 5.1.4 on 2024-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, choices=[('DEVELOPPEMENT WEB', 'DEVELOPPEMENT WEB'), ('MARKETING DIGITAL', 'MARKETING DIGITAL'), ('DEVELOPPEMENT MOBILE', 'DEVELOPPEMENT MOBILE')], max_length=255, null=True),
        ),
    ]
