# Generated by Django 5.1.4 on 2024-12-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_archive_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_updated']},
        ),
    ]
